// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TransportTracker.Api.Data;

#nullable disable

namespace TransportTracker.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261001022547_AddObservations")]
    partial class AddObservations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TransportTracker.Api.Poller.Observation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int?>("DelaySeconds")
                        .HasColumnType("integer")
                        .HasColumnName("delay_seconds");

                    b.Property<short?>("DirectionId")
                        .HasColumnType("smallint")
                        .HasColumnName("direction_id");

                    b.Property<string>("Headsign")
                        .HasColumnType("text")
                        .HasColumnName("headsign");

                    b.Property<string>("Line")
                        .HasColumnType("text")
                        .HasColumnName("line");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<DateTimeOffset>("ScheduledAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scheduled_at");

                    b.Property<DateOnly>("ServiceDate")
                        .HasColumnType("date")
                        .HasColumnName("service_date");

                    b.Property<string>("StationId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("station_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<string>("TripId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.HasKey("Id")
                        .HasName("pk_observations");

                    b.HasIndex("StationId", "ScheduledAt")
                        .HasDatabaseName("ix_observations_station_id_scheduled_at");

                    b.HasIndex("ServiceDate", "TripId", "StationId", "ScheduledAt")
                        .IsUnique()
                        .HasDatabaseName("ix_observations_service_date_trip_id_station_id_scheduled_at");

                    b.ToTable("observations", (string)null);
                });

            modelBuilder.Entity("TransportTracker.Api.Timetable.Route", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer")
                        .HasColumnName("import_id");

                    b.Property<string>("RouteId")
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("AgencyId")
                        .HasColumnType("text")
                        .HasColumnName("agency_id");

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("LongName")
                        .HasColumnType("text")
                        .HasColumnName("long_name");

                    b.Property<string>("ShortName")
                        .HasColumnType("text")
                        .HasColumnName("short_name");

                    b.Property<string>("TextColor")
                        .HasColumnType("text")
                        .HasColumnName("text_color");

                    b.HasKey("ImportId", "RouteId")
                        .HasName("pk_routes");

                    b.ToTable("routes", (string)null);
                });

            modelBuilder.Entity("TransportTracker.Api.Timetable.ServiceCalendar", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer")
                        .HasColumnName("import_id");

                    b.Property<string>("ServiceId")
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("Friday")
                        .HasColumnType("boolean")
                        .HasColumnName("friday");

                    b.Property<bool>("Monday")
                        .HasColumnType("boolean")
                        .HasColumnName("monday");

                    b.Property<bool>("Saturday")
                        .HasColumnType("boolean")
                        .HasColumnName("saturday");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<bool>("Sunday")
                        .HasColumnType("boolean")
                        .HasColumnName("sunday");

                    b.Property<bool>("Thursday")
                        .HasColumnType("boolean")
                        .HasColumnName("thursday");

                    b.Property<bool>("Tuesday")
                        .HasColumnType("boolean")
                        .HasColumnName("tuesday");

                    b.Property<bool>("Wednesday")
                        .HasColumnType("boolean")
                        .HasColumnName("wednesday");

                    b.HasKey("ImportId", "ServiceId")
                        .HasName("pk_service_calendars");

                    b.ToTable("service_calendars", (string)null);
                });

            modelBuilder.Entity("TransportTracker.Api.Timetable.Stop", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer")
                        .HasColumnName("import_id");

                    b.Property<string>("StopId")
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.Property<double>("Lat")
                        .HasColumnType("double precision")
                        .HasColumnName("lat");

                    b.Property<short>("LocationType")
                        .HasColumnType("smallint")
                        .HasColumnName("location_type");

                    b.Property<double>("Lon")
                        .HasColumnType("double precision")
                        .HasColumnName("lon");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("ParentStation")
                        .HasColumnType("text")
                        .HasColumnName("parent_station");

                    b.HasKey("ImportId", "StopId")
                        .HasName("pk_stops");

                    b.HasIndex("ImportId", "ParentStation")
                        .HasDatabaseName("ix_stops_import_id_parent_station");

                    b.ToTable("stops", (string)null);
                });

            modelBuilder.Entity("TransportTracker.Api.Timetable.StopTime", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer")
                        .HasColumnName("import_id");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<int>("StopSequence")
                        .HasColumnType("integer")
                        .HasColumnName("stop_sequence");

                    b.Property<int?>("ArrivalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("arrival_seconds");

                    b.Property<int?>("DepartureSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("departure_seconds");

                    b.Property<short>("DropOffType")
                        .HasColumnType("smallint")
                        .HasColumnName("drop_off_type");

                    b.Property<short>("PickupType")
                        .HasColumnType("smallint")
                        .HasColumnName("pickup_type");

                    b.Property<string>("StopId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("stop_id");

                    b.HasKey("ImportId", "TripId", "StopSequence")
                        .HasName("pk_stop_times");

                    b.HasIndex("ImportId", "StopId")
                        .HasDatabaseName("ix_stop_times_import_id_stop_id");

                    b.ToTable("stop_times", (string)null);
                });

            modelBuilder.Entity("TransportTracker.Api.Timetable.TimetableImport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_hash");

                    b.Property<DateTimeOffset>("ImportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("imported_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<DateTimeOffset?>("SourceLastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("source_last_modified");

                    b.Property<long>("StopTimeCount")
                        .HasColumnType("bigint")
                        .HasColumnName("stop_time_count");

                    b.HasKey("Id")
                        .HasName("pk_timetable_imports");

                    b.HasIndex("IsActive")
                        .IsUnique()
                        .HasDatabaseName("ix_timetable_imports_is_active")
                        .HasFilter("is_active");

                    b.ToTable("timetable_imports", (string)null);
                });

            modelBuilder.Entity("TransportTracker.Api.Timetable.Trip", b =>
                {
                    b.Property<int>("ImportId")
                        .HasColumnType("integer")
                        .HasColumnName("import_id");

                    b.Property<string>("TripId")
                        .HasColumnType("text")
                        .HasColumnName("trip_id");

                    b.Property<short?>("DirectionId")
                        .HasColumnType("smallint")
                        .HasColumnName("direction_id");

                    b.Property<string>("Headsign")
                        .HasColumnType("text")
                        .HasColumnName("headsign");

                    b.Property<string>("RouteId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("route_id");

                    b.Property<string>("ServiceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("service_id");

                    b.HasKey("ImportId", "TripId")
                        .HasName("pk_trips");

                    b.ToTable("trips", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
